directory: /media/pi/Lexar/music/complete
library: /media/pi/Lexar/musiclibrary.db

import:
  move: yes
  copy: no
  write: yes
  resume: ask
  incremental: yes

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title

plugins: fetchart lastgenre lyrics scrub zero
fetchart:
  sources: coverart itunes amazon albumart
lyrics:
  sources: genius musixmatch
lastgenre:
  canonical: yes
  source: album
zero:
  fields: comments
